// apps/web/src/routes/settings/+page.svelte
<script lang="ts">
  import Icon from '$lib/components/Icon.svelte'
  import { clearConfig, loadConfig, saveConfig } from '$lib/nextcloud'

  const STATUS_MS = 4000

  const stored = loadConfig()

  let serverUrl = $state(stored?.serverUrl ?? '')
  let username = $state(stored?.username ?? '')
  let password = $state(stored?.password ?? '')
  let formError = $state<string | null>(null)
  let status = $state<string | null>(null)
  let statusTimer: ReturnType<typeof setTimeout> | null = null

  let isConfigured = $derived(serverUrl.trim() !== '' && username.trim() !== '')

  function showStatus(message: string) {
    status = message
    if (statusTimer) clearTimeout(statusTimer)
    statusTimer = setTimeout(() => (status = null), STATUS_MS)
  }

  function save(event: SubmitEvent) {
    event.preventDefault()
    if (!serverUrl.trim() || !username.trim() || !password.trim()) {
      formError = 'Bitte fülle alle Felder aus.'
      return
    }
    formError = null
    saveConfig({ serverUrl: serverUrl.trim(), username: username.trim(), password })
    showStatus('Einstellungen gespeichert')
  }

  function clear() {
    if (!confirm('Zugangsdaten entfernen? Dies löscht nur die gespeicherte Server-Konfiguration, nicht deine lokalen Daten.')) return
    clearConfig()
    serverUrl = ''
    username = ''
    password = ''
    formError = null
    showStatus('Zugangsdaten entfernt')
  }
</script>

<header class="head">
  <a class="head__action" href="/" aria-label="Zurück">
    <Icon name="back" color="#ffffff" />
  </a>
  <h1 class="head__title">NextCloud Sync</h1>
  <span class="head__spacer"></span>
</header>

<form class="form" onsubmit={save}>
  <div class="form__fields">
    <h2 class="section">Server-Verbindung</h2>

    <label class="field">
      <span class="field__label">Server-URL</span>
      <input
        class="field__input"
        type="url"
        inputmode="url"
        bind:value={serverUrl}
        placeholder="https://nextcloud.example.com"
        autocapitalize="none"
        autocorrect="off"
      />
    </label>

    <label class="field">
      <span class="field__label">Benutzername</span>
      <input
        class="field__input"
        bind:value={username}
        placeholder="Benutzername"
        autocapitalize="none"
        autocorrect="off"
        autocomplete="username"
      />
    </label>

    <label class="field">
      <span class="field__label">Passwort / App-Passwort</span>
      <input
        class="field__input"
        type="password"
        bind:value={password}
        placeholder="Passwort"
        autocomplete="current-password"
      />
      <span class="field__hint">
        Nutze ein NextCloud App-Passwort — es wird unverschlüsselt in diesem Browser gespeichert
        und lässt sich jederzeit widerrufen.
      </span>
    </label>

    {#if formError}
      <span class="field__error">{formError}</span>
    {/if}

    {#if status}
      <p class="status">{status}</p>
    {/if}
  </div>

  <div class="form__actions">
    <button class="submit" type="submit">Speichern</button>
    {#if isConfigured}
      <button class="destructive" type="button" onclick={clear}>Zugangsdaten entfernen</button>
    {/if}
  </div>
</form>

<style lang="scss">
  @use '$lib/styles/tokens' as *;

  .head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.75rem 1.25rem 1rem;

    &__action {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 2.5rem;
      height: 2.5rem;
      border: 1px solid $color-border;
      border-radius: 999px;
      background: $color-card;
      cursor: pointer;
    }

    &__title {
      font-size: 1rem;
      font-weight: 700;
    }

    &__spacer {
      width: 2.5rem;
    }
  }

  .form {
    display: flex;
    flex: 1;
    flex-direction: column;

    &__fields {
      flex: 1;
      padding: 0 1.25rem 2rem;
    }

    &__actions {
      padding: 0.5rem 1.25rem safe-bottom(1rem);
    }
  }

  .section {
    color: $color-text-secondary;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.15em;
  }

  .field {
    display: block;
    margin-top: 1.25rem;

    &__label {
      display: block;
      margin-bottom: 0.5rem;
      color: $color-text-secondary;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.15em;
    }

    &__input {
      display: block;
      width: 100%;
      padding: 0.75rem 1rem;
      border: 1px solid $color-border;
      border-radius: 0.75rem;
      background: $color-card;
      color: $color-text-primary;
      outline: none;

      &::placeholder {
        color: $color-text-muted;
      }

      &:focus {
        border-color: $color-accent-dark;
      }
    }

    &__hint {
      display: block;
      margin-top: 0.5rem;
      color: $color-text-muted;
      font-size: 0.75rem;
    }

    &__error {
      display: block;
      margin-top: 1.25rem;
      color: $color-error;
      font-size: 0.75rem;
    }
  }

  .status {
    margin-top: 1.25rem;
    padding: 0.75rem 1rem;
    border: 1px solid $color-border;
    border-radius: 0.75rem;
    background: $color-card;
    font-size: 0.875rem;
  }

  .submit {
    width: 100%;
    padding: 1rem;
    border: none;
    border-radius: 1rem;
    background: $color-accent;
    color: $color-background;
    font-size: 1rem;
    font-weight: 700;
    cursor: pointer;
  }

  .destructive {
    width: 100%;
    padding: 0.75rem;
    margin-top: 0.75rem;
    border: none;
    background: none;
    color: $color-error;
    font-size: 0.875rem;
    font-weight: 600;
    cursor: pointer;
  }
</style>

// apps/mobile/app/settings.tsx
import React, { useCallback, useEffect, useState } from 'react'
import {
  View, Text, TextInput, Pressable, ScrollView, Alert,
  KeyboardAvoidingView, Platform, ActivityIndicator,
} from 'react-native'
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context'
import { useRouter } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import {
  loadConfig, saveConfig, clearConfig, testConnection,
  uploadToNextCloud, downloadFromNextCloud,
} from '../lib/nextcloud'

export default function SettingsScreen() {
  const router = useRouter()
  const insets = useSafeAreaInsets()

  const [serverUrl, setServerUrl] = useState('')
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [saving, setSaving] = useState(false)
  const [testing, setTesting] = useState(false)
  const [syncing, setSyncing] = useState<'upload' | 'download' | null>(null)
  const [status, setStatus] = useState<string | null>(null)

  useEffect(() => {
    loadConfig().then((cfg) => {
      if (cfg) {
        setServerUrl(cfg.serverUrl)
        setUsername(cfg.username)
        setPassword(cfg.password)
      }
    })
  }, [])

  const showStatus = useCallback((msg: string) => {
    setStatus(msg)
    setTimeout(() => setStatus(null), 4000)
  }, [])

  const handleSave = async () => {
    if (!serverUrl.trim() || !username.trim() || !password.trim()) {
      Alert.alert('Fehler', 'Bitte fülle alle Felder aus.')
      return
    }
    setSaving(true)
    try {
      await saveConfig({ serverUrl: serverUrl.trim(), username: username.trim(), password })
      showStatus('Einstellungen gespeichert')
    } catch {
      showStatus('Fehler beim Speichern')
    } finally {
      setSaving(false)
    }
  }

  const handleTest = async () => {
    if (!serverUrl.trim() || !username.trim() || !password.trim()) {
      Alert.alert('Fehler', 'Bitte fülle alle Felder aus.')
      return
    }
    setTesting(true)
    const result = await testConnection({ serverUrl: serverUrl.trim(), username: username.trim(), password })
    setTesting(false)
    if (result.ok) {
      showStatus('Verbindung erfolgreich')
    } else {
      showStatus(result.error)
    }
  }

  const handleUpload = async () => {
    setSyncing('upload')
    const result = await uploadToNextCloud({ serverUrl: serverUrl.trim(), username: username.trim(), password })
    setSyncing(null)
    if (result.ok) {
      showStatus('Backup hochgeladen')
    } else {
      showStatus(result.error)
    }
  }

  const handleDownload = async () => {
    setSyncing('download')
    const result = await downloadFromNextCloud({ serverUrl: serverUrl.trim(), username: username.trim(), password })
    setSyncing(null)
    if (result.ok) {
      showStatus('Backup wiederhergestellt')
    } else {
      showStatus(result.error)
    }
  }

  const handleClear = () => {
    Alert.alert('Zugangsdaten entfernen?', 'Dies löscht nur die gespeicherte Server-Konfiguration, nicht deine lokalen Daten.', [
      { text: 'Abbrechen', style: 'cancel' },
      {
        text: 'Entfernen', style: 'destructive',
        onPress: async () => {
          await clearConfig()
          setServerUrl('')
          setUsername('')
          setPassword('')
          showStatus('Zugangsdaten entfernt')
        },
      },
    ])
  }

  const isConfigured = serverUrl.trim() && username.trim()

  return (
    <SafeAreaView className="flex-1 bg-background" edges={['top']}>
      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} className="flex-1">
        <View className="flex-row items-center justify-between px-5 pt-3 pb-4">
          <Pressable
            onPress={() => router.back()}
            className="w-10 h-10 rounded-full bg-card border border-border items-center justify-center"
          >
            <Ionicons name="chevron-back" size={20} color="#fff" />
          </Pressable>
          <Text className="text-white text-base font-bold">NextCloud Sync</Text>
          <View style={{ width: 40 }} />
        </View>

        <ScrollView className="flex-1 px-5" keyboardShouldPersistTaps="handled">
          <Text className="text-text-secondary text-xs font-semibold uppercase tracking-widest mb-4">
            Server-Verbindung
          </Text>

          <Text className="text-text-muted text-xs mb-2">Server-URL</Text>
          <TextInput
            value={serverUrl}
            onChangeText={setServerUrl}
            placeholder="https://nextcloud.example.com"
            placeholderTextColor="#525252"
            autoCapitalize="none"
            autoCorrect={false}
            keyboardType="url"
            className="bg-card border border-border rounded-xl px-4 py-3 text-white mb-4"
          />

          <Text className="text-text-muted text-xs mb-2">Benutzername</Text>
          <TextInput
            value={username}
            onChangeText={setUsername}
            placeholder="Benutzername"
            placeholderTextColor="#525252"
            autoCapitalize="none"
            autoCorrect={false}
            className="bg-card border border-border rounded-xl px-4 py-3 text-white mb-4"
          />

          <Text className="text-text-muted text-xs mb-2">Passwort / App-Passwort</Text>
          <TextInput
            value={password}
            onChangeText={setPassword}
            placeholder="Passwort"
            placeholderTextColor="#525252"
            secureTextEntry
            className="bg-card border border-border rounded-xl px-4 py-3 text-white mb-6"
          />

          <View className="flex-row gap-3 mb-6">
            <Pressable
              onPress={handleSave}
              disabled={saving}
              className="flex-1 bg-accent rounded-xl py-3 items-center active:opacity-80"
            >
              {saving ? (
                <ActivityIndicator size="small" color="#0a0a0a" />
              ) : (
                <Text className="text-background font-bold text-sm">Speichern</Text>
              )}
            </Pressable>
            <Pressable
              onPress={handleTest}
              disabled={testing}
              className="flex-1 bg-card border border-border rounded-xl py-3 items-center active:opacity-80"
            >
              {testing ? (
                <ActivityIndicator size="small" color="#a3a3a3" />
              ) : (
                <Text className="text-white font-bold text-sm">Testen</Text>
              )}
            </Pressable>
          </View>

          {status && (
            <View className="bg-card border border-border rounded-xl px-4 py-3 mb-6">
              <Text className="text-white text-sm">{status}</Text>
            </View>
          )}

          {isConfigured && (
            <>
              <Text className="text-text-secondary text-xs font-semibold uppercase tracking-widest mb-4">
                Backup & Wiederherstellung
              </Text>
              <Text className="text-text-muted text-xs mb-4 leading-5">
                Die Datenbank wird in der Cloud unter {'{Server}/remote.php/dav/files/{Benutzer}/LindyHop/'} gespeichert.
              </Text>

              <Pressable
                onPress={handleUpload}
                disabled={syncing !== null}
                className="bg-accent rounded-2xl py-4 items-center mb-3 active:opacity-80"
              >
                {syncing === 'upload' ? (
                  <ActivityIndicator size="small" color="#0a0a0a" />
                ) : (
                  <Text className="text-background font-bold text-base">⬆ Backup hochladen</Text>
                )}
              </Pressable>

              <Pressable
                onPress={handleDownload}
                disabled={syncing !== null}
                className="bg-card border border-accent rounded-2xl py-4 items-center mb-6 active:opacity-80"
              >
                {syncing === 'download' ? (
                  <ActivityIndicator size="small" color="#f59e0b" />
                ) : (
                  <Text className="text-accent font-bold text-base">⬇ Backup herunterladen</Text>
                )}
              </Pressable>
            </>
          )}

          {isConfigured && (
            <Pressable
              onPress={handleClear}
              className="py-3 items-center mb-8"
            >
              <Text className="text-error text-sm font-semibold">Zugangsdaten entfernen</Text>
            </Pressable>
          )}
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  )
}
