// apps/mobile/app/entry/[id].tsx
import React, { useMemo, useRef } from 'react'
import { View, Text, Pressable, Alert } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import { EntryForm } from '../../components/EntryForm'
import { deleteEntry, getEntry, updateEntry } from '../../db/queries'
import { deleteVideo } from '../../lib/videoStorage'

export default function EntryDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>()
  const router = useRouter()
  const entryId = Number(id)
  const entry = useMemo(() => getEntry(entryId), [entryId])

  const originalVideo = useRef<string | null>(entry?.video_uri ?? null)
  const currentVideo = useRef<string | null>(entry?.video_uri ?? null)

  if (!entry) {
    return (
      <SafeAreaView className="flex-1 bg-background items-center justify-center">
        <Text className="text-white">Eintrag nicht gefunden.</Text>
      </SafeAreaView>
    )
  }

  const handleDelete = () => {
    Alert.alert('Löschen?', `„${entry.name}" wirklich entfernen?`, [
      { text: 'Abbrechen', style: 'cancel' },
      {
        text: 'Löschen',
        style: 'destructive',
        onPress: async () => {
          await deleteVideo(currentVideo.current)
          deleteEntry(entry.id)
          router.back()
        },
      },
    ])
  }

  const handleBack = async () => {
    const current = currentVideo.current
    const original = originalVideo.current
    if (current && current !== original) {
      await deleteVideo(current)
    }
    router.back()
  }

  const handleSave = async (values: Parameters<
    React.ComponentProps<typeof EntryForm>['onSubmit']
  >[0]) => {
    updateEntry(entry.id, values)
    const original = originalVideo.current
    if (original && original !== values.video_uri) {
      await deleteVideo(original)
    }
    originalVideo.current = values.video_uri
    router.back()
  }

  return (
    <SafeAreaView className="flex-1 bg-background" edges={['top']}>
      <View className="flex-row items-center justify-between px-5 pt-3 pb-4">
        <Pressable
          onPress={handleBack}
          className="w-10 h-10 rounded-full bg-card border border-border items-center justify-center"
        >
          <Ionicons name="chevron-back" size={20} color="#fff" />
        </Pressable>
        <Text className="text-white text-base font-bold">Eintrag</Text>
        <Pressable
          onPress={handleDelete}
          className="w-10 h-10 rounded-full bg-card border border-border items-center justify-center"
        >
          <Ionicons name="trash-outline" size={18} color="#ef4444" />
        </Pressable>
      </View>

      <EntryForm
        initial={{
          name: entry.name,
          art: entry.art,
          taktzahl: entry.taktzahl,
          video_uri: entry.video_uri,
          tags: entry.tags,
          note: entry.note,
        }}
        submitLabel="Änderungen speichern"
        onVideoChange={(uri) => {
          currentVideo.current = uri
        }}
        onSubmit={handleSave}
      />
    </SafeAreaView>
  )
}

// apps/web/src/routes/entry/[id]/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import EntryForm from '$lib/components/EntryForm.svelte'
  import Icon from '$lib/components/Icon.svelte'
  import { deleteEntry, getEntry, updateEntry, type Entry, type EntryInput } from '$lib/db/queries'
  import { reload } from '$lib/stores/entries'
  import { deleteVideo } from '$lib/videoStorage'

  let entry = $state<Entry | null>(null)
  let loaded = $state(false)

  // Same rule as the RN version: track the video the entry started with against
  // the one currently selected, and delete whichever ends up orphaned.
  let originalVideo: string | null = null
  let currentVideo: string | null = null

  $effect(() => {
    const id = Number(page.params.id)
    void getEntry(id).then((found) => {
      entry = found
      loaded = true
      originalVideo = found?.video_uri ?? null
      currentVideo = found?.video_uri ?? null
    })
  })

  async function back() {
    if (currentVideo && currentVideo !== originalVideo) await deleteVideo(currentVideo)
    await goto('/')
  }

  async function remove() {
    if (!entry) return
    if (!confirm(`„${entry.name}" wirklich entfernen?`)) return
    await deleteVideo(currentVideo)
    await deleteEntry(entry.id)
    reload()
    await goto('/')
  }

  async function save(values: EntryInput) {
    if (!entry) return
    await updateEntry(entry.id, values)
    if (originalVideo && originalVideo !== values.video_uri) await deleteVideo(originalVideo)
    originalVideo = values.video_uri
    reload()
    await goto('/')
  }
</script>

<header class="head">
  <button class="head__action" type="button" onclick={back} aria-label="Zurück">
    <Icon name="back" color="#ffffff" />
  </button>
  <h1 class="head__title">Eintrag</h1>
  <button class="head__action" type="button" onclick={remove} aria-label="Löschen">
    <Icon name="trash" size={18} color="#ef4444" />
  </button>
</header>

{#if !loaded}
  <p class="notice">Lädt …</p>
{:else if !entry}
  <p class="notice">Eintrag nicht gefunden.</p>
{:else}
  <EntryForm
    initial={{
      name: entry.name,
      art: entry.art,
      taktzahl: entry.taktzahl,
      video_uri: entry.video_uri,
      tags: entry.tags,
      note: entry.note,
    }}
    submitLabel="Änderungen speichern"
    onvideochange={(uri) => (currentVideo = uri)}
    onsubmit={save}
  />
{/if}

<style lang="scss">
  @use '$lib/styles/tokens' as *;

  .head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.75rem 1.25rem 1rem;

    &__action {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 2.5rem;
      height: 2.5rem;
      border: 1px solid $color-border;
      border-radius: 999px;
      background: $color-card;
      cursor: pointer;
    }

    &__title {
      font-size: 1rem;
      font-weight: 700;
    }
  }

  .notice {
    padding: 2rem 1.25rem;
    text-align: center;
    color: $color-text-secondary;
  }
</style>
