// apps/mobile/components/EntryCard.tsx
import React from 'react'
import { View, Text, Pressable } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { ART_LABELS } from '../db/schema'
import type { Entry } from '../db/queries'
import { Highlight } from './Highlight'

interface Props {
  entry: Entry
  onPress: () => void
  search?: string
}

export function EntryCard({ entry, onPress, search }: Props) {
  const tags = entry.tags
    .split(',')
    .map((t) => t.trim())
    .filter(Boolean)

  return (
    <Pressable
      onPress={onPress}
      className="bg-card border border-border rounded-2xl p-4 active:opacity-80"
    >
      <View className="flex-row items-start justify-between">
        <View className="flex-1 pr-3">
          <Highlight
            text={entry.name}
            query={search}
            className="text-white text-lg font-bold"
            numberOfLines={1}
          />
          <View className="flex-row items-center gap-3 mt-1">
            <Text className="text-accent text-xs font-semibold uppercase tracking-wider">
              {ART_LABELS[entry.art]}
            </Text>
            <Text className="text-text-secondary text-xs">
              {entry.taktzahl} Takte
            </Text>
          </View>
        </View>
        <View className="items-center justify-center w-9 h-9 rounded-full bg-background">
          <Ionicons
            name={entry.video_uri ? 'play' : 'document-text-outline'}
            size={16}
            color={entry.video_uri ? '#f59e0b' : '#525252'}
          />
        </View>
      </View>

      {entry.note ? (
        <Highlight
          text={entry.note}
          query={search}
          className="text-text-secondary text-sm mt-3 leading-5"
          numberOfLines={2}
        />
      ) : null}

      {tags.length > 0 ? (
        <View className="flex-row flex-wrap gap-2 mt-3">
          {tags.slice(0, 4).map((t) => (
            <View
              key={t}
              className="px-2 py-0.5 rounded-full border bg-background border-border"
            >
              <Highlight
                text={`#${t}`}
                query={search}
                className="text-text-secondary text-xs"
              />
            </View>
          ))}
        </View>
      ) : null}
    </Pressable>
  )
}

// apps/web/src/lib/components/EntryCard.svelte
<script lang="ts">
  import Highlight from './Highlight.svelte'
  import Icon from './Icon.svelte'
  import { ART_LABELS } from '$lib/db/schema'
  import type { Entry } from '$lib/db/queries'

  interface Props {
    entry:   Entry
    search?: string
  }

  let { entry, search = '' }: Props = $props()

  let tags = $derived(
    entry.tags
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean)
      .slice(0, 4)
  )
</script>

<a class="card" href="/entry/{entry.id}">
  <div class="card__head">
    <div class="card__title">
      <span class="card__name"><Highlight text={entry.name} query={search} lines={1} /></span>
      <div class="card__meta">
        <span class="card__art">{ART_LABELS[entry.art]}</span>
        <span class="card__takte">{entry.taktzahl} Takte</span>
      </div>
    </div>
    <span class="card__badge" data-video={entry.video_uri ? 'true' : 'false'}>
      <Icon
        name={entry.video_uri ? 'play' : 'document'}
        size={16}
        color={entry.video_uri ? '#f59e0b' : '#525252'}
      />
    </span>
  </div>

  {#if entry.note}
    <p class="card__note"><Highlight text={entry.note} query={search} lines={2} /></p>
  {/if}

  {#if tags.length > 0}
    <div class="card__tags">
      {#each tags as tag (tag)}
        <span class="card__tag"><Highlight text="#{tag}" query={search} /></span>
      {/each}
    </div>
  {/if}
</a>

<style lang="scss">
  @use '$lib/styles/tokens' as *;

  .card {
    display: block;
    padding: 1rem;
    border: 1px solid $color-border;
    border-radius: 1rem;
    background: $color-card;
    color: inherit;
    text-decoration: none;

    &:active {
      opacity: 0.8;
    }

    &__head {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: 0.75rem;
    }

    &__title {
      flex: 1;
      min-width: 0;
    }

    &__name {
      display: block;
      font-size: 1.125rem;
      font-weight: 700;
      color: $color-text-primary;
    }

    &__meta {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-top: 0.25rem;
    }

    &__art {
      color: $color-accent;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    &__takte {
      color: $color-text-secondary;
      font-size: 0.75rem;
    }

    &__badge {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 2.25rem;
      height: 2.25rem;
      border-radius: 999px;
      background: $color-background;
    }

    &__note {
      margin: 0.75rem 0 0;
      color: $color-text-secondary;
      font-size: 0.875rem;
      line-height: 1.4;
    }

    &__tags {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
      margin-top: 0.75rem;
    }

    &__tag {
      padding: 0.125rem 0.5rem;
      border: 1px solid $color-border;
      border-radius: 999px;
      background: $color-background;
      color: $color-text-secondary;
      font-size: 0.75rem;
    }
  }
</style>
