// apps/mobile/app/entry/new.tsx
import React, { useRef } from 'react'
import { View, Text, Pressable } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useRouter } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import { EntryForm } from '../../components/EntryForm'
import { createEntry } from '../../db/queries'
import { deleteVideo } from '../../lib/videoStorage'

export default function NewEntryScreen() {
  const router = useRouter()
  const pendingVideo = useRef<string | null>(null)

  const handleCancel = async () => {
    if (pendingVideo.current) await deleteVideo(pendingVideo.current)
    router.back()
  }

  return (
    <SafeAreaView className="flex-1 bg-background" edges={['top']}>
      <View className="flex-row items-center justify-between px-5 pt-3 pb-4">
        <Pressable
          onPress={handleCancel}
          className="w-10 h-10 rounded-full bg-card border border-border items-center justify-center"
        >
          <Ionicons name="close" size={20} color="#fff" />
        </Pressable>
        <Text className="text-white text-base font-bold">Neuer Eintrag</Text>
        <View style={{ width: 40 }} />
      </View>

      <EntryForm
        submitLabel="Speichern"
        onVideoChange={(uri) => {
          pendingVideo.current = uri
        }}
        onSubmit={(values) => {
          createEntry(values)
          pendingVideo.current = null
          router.back()
        }}
      />
    </SafeAreaView>
  )
}

// apps/web/src/routes/entry/new/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import EntryForm from '$lib/components/EntryForm.svelte'
  import Icon from '$lib/components/Icon.svelte'
  import { createEntry, type EntryInput } from '$lib/db/queries'
  import { reload } from '$lib/stores/entries'
  import { deleteVideo } from '$lib/videoStorage'

  // A video picked and then abandoned by cancelling would otherwise sit in OPFS
  // forever with no entry pointing at it.
  let pendingVideo: string | null = null

  async function cancel() {
    if (pendingVideo) await deleteVideo(pendingVideo)
    await goto('/')
  }

  async function save(values: EntryInput) {
    await createEntry(values)
    pendingVideo = null
    reload()
    await goto('/')
  }
</script>

<header class="head">
  <button class="head__action" type="button" onclick={cancel} aria-label="Abbrechen">
    <Icon name="close" color="#ffffff" />
  </button>
  <h1 class="head__title">Neuer Eintrag</h1>
  <span class="head__spacer"></span>
</header>

<EntryForm
  submitLabel="Speichern"
  onvideochange={(uri) => (pendingVideo = uri)}
  onsubmit={save}
/>

<style lang="scss">
  @use '$lib/styles/tokens' as *;

  .head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.75rem 1.25rem 1rem;

    &__action {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 2.5rem;
      height: 2.5rem;
      border: 1px solid $color-border;
      border-radius: 999px;
      background: $color-card;
      cursor: pointer;
    }

    &__title {
      font-size: 1rem;
      font-weight: 700;
    }

    &__spacer {
      width: 2.5rem;
    }
  }
</style>
