// apps/web/src/lib/components/FilterChip.svelte
<script lang="ts">
  interface Props {
    label:   string
    active:  boolean
    onclick: () => void
  }

  let { label, active, onclick }: Props = $props()
</script>

<button class="chip" type="button" data-active={active} {onclick}>{label}</button>

<style lang="scss">
  @use '$lib/styles/tokens' as *;

  .chip {
    padding: 0.5rem 1rem;
    border: 1px solid $color-border;
    border-radius: 999px;
    background: $color-card;
    color: $color-text-primary;
    font-size: 0.875rem;
    font-weight: 600;
    cursor: pointer;

    &[data-active='true'] {
      background: $color-accent;
      border-color: $color-accent;
      color: $color-background;
    }
  }
</style>

// apps/mobile/components/FilterChip.tsx
import React from 'react'
import { Text, Pressable } from 'react-native'

interface Props {
  label: string
  active: boolean
  onPress: () => void
}

export function FilterChip({ label, active, onPress }: Props) {
  return (
    <Pressable
      onPress={onPress}
      className={`px-4 py-2 rounded-full border ${
        active ? 'bg-accent border-accent' : 'bg-card border-border'
      }`}
    >
      <Text
        className={`text-sm font-semibold ${
          active ? 'text-background' : 'text-text-primary'
        }`}
      >
        {label}
      </Text>
    </Pressable>
  )
}
