// apps/web/src/lib/components/Segmented.svelte
<script lang="ts" generics="T extends string | number | boolean">
  interface Option {
    value: T
    label: string
  }

  interface Props {
    options:  Option[]
    value:    T
    onchange: (next: T) => void
  }

  let { options, value, onchange }: Props = $props()
</script>

<div class="segmented">
  {#each options as option (option.value)}
    <button
      class="segmented__option"
      type="button"
      data-active={option.value === value}
      onclick={() => onchange(option.value)}
    >
      {option.label}
    </button>
  {/each}
</div>

<style lang="scss">
  @use '$lib/styles/tokens' as *;

  .segmented {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;

    &__option {
      padding: 0.5rem 1rem;
      border: 1px solid $color-border;
      border-radius: 999px;
      background: $color-card;
      color: $color-text-primary;
      font-size: 0.875rem;
      font-weight: 600;
      cursor: pointer;

      &[data-active='true'] {
        background: $color-accent;
        border-color: $color-accent;
        color: $color-background;
      }
    }
  }
</style>

// apps/mobile/components/Segmented.tsx
import React from 'react'
import { View, Text, Pressable } from 'react-native'

interface Option<T> {
  value: T
  label: string
}

interface Props<T extends string | number> {
  options: Option<T>[]
  value: T
  onChange: (next: T) => void
}

export function Segmented<T extends string | number>({
  options,
  value,
  onChange,
}: Props<T>) {
  return (
    <View className="flex-row flex-wrap gap-2">
      {options.map((opt) => {
        const active = opt.value === value
        return (
          <Pressable
            key={String(opt.value)}
            onPress={() => onChange(opt.value)}
            className={`px-4 py-2 rounded-full border ${
              active
                ? 'bg-accent border-accent'
                : 'bg-card border-border'
            }`}
          >
            <Text
              className={`text-sm font-semibold ${
                active ? 'text-background' : 'text-text-primary'
              }`}
            >
              {opt.label}
            </Text>
          </Pressable>
        )
      })}
    </View>
  )
}
